### PR TITLE
feat: support for french and PHP 8

### PR DESCRIPTION
**Pull request by Goutte**
I also have a small change in `phpunit.xml` (automatic migration of format) that I stashed because it might break on older phpunit, and new ones only show a deprecation notice.

---

Pretty neat use of `SplStack` !  :clap: :clap: 

---

Good day !

### CODE REVIEW

**Comment by djunehor** [comment]
Hello.
Thanks for the PR.
Please update your PR to make sure the tests are passing.

**Comment by Goutte** [comment]
Hello !

```
  Problem 1
    - Installation request for kwn/number-to-words dev-master -> satisfiable by kwn/number-to-words[dev-master].
    - kwn/number-to-words dev-master requires php >=7.4 -> your PHP version (7.3.15) does not satisfy that requirement.
```

I had been wondering why `number-to-words` was pinned to `dev-master` ?

I can try to guess a working release, I suppose.
Do you remember why you pinned `number-to-words` to `dev-master`  ?

**Comment by djunehor** [comment]
> Hello !
> 
> ```
>   Problem 1
>     - Installation request for kwn/number-to-words dev-master -> satisfiable by kwn/number-to-words[dev-master].
>     - kwn/number-to-words dev-master requires php >=7.4 -> your PHP version (7.3.15) does not satisfy that requirement.
> ```
> 
> I had been wondering why `number-to-words` was pinned to `dev-master` ?
> 
> I can try to guess a working release, I suppose. Do you remember why you pinned `number-to-words` to `dev-master` ?

Unfortunately, I don't. You can change the target branch if that fixes the problem.

**Comment by Goutte** [comment]
@djunehor All done !

I took the liberty of adding some aliases for zero that I use.  If you don't want them I can revert those and implement them in my gherkin tools wrapper instead.  They kind of make sense and should be innocuous.

**Pull request merged**
